### ISSUE TITLE
Site otakusan.net bị lỗi khi yêu cầu tải

### ISSUE THREAD

**Issue by Horigamisan** [lelinhtinh/Userscript#101]
![image](https://user-images.githubusercontent.com/87481608/147758880-b3aef5f4-ef26-4793-bcf5-da88596c821b.png)
Không thể tải truyện ở site otakusan.net, hiển thị lỗi không có dữ liệu ở bất kì truyện nào.

**Comment by quyentruong** [comment]
Mình đọc thử source code phần otakusan. Thấy là khá phức tạp. Function otakuSanFilter giống như là đang giải puzzle. Mình không hiểu sao có quá nhiều website trong đó (Chả nhẽ otakusan leech truyện từ chỗ khác ??)

**Comment by lelinhtinh** [comment]
Trang nào cũng leech cả mà, lúc trước vì lấy link từ tùm lum chỗ nên phải có một đoạn code sửa lại link cho đúng. Giờ hầu hết đều dùng CDN riêng nên cái `otakuSanFilter` đấy bỏ đi cũng được rồi.

**Comment by lelinhtinh** [comment]
Fixed at [v3.3.0](https://github.com/lelinhtinh/Userscript/commit/a9a7ff04fc05c732c6930aa97f550cede0f1e05e)

**Comment by quyentruong** [comment]
otakusan load chậm quá nên mình không test được với script mới

**Comment by lelinhtinh** [comment]
Tối qua mạng lag ấy. Ngồi fix cái truyensieuhay mà nó cứ pending mãi, cứ ngỡ code sai chớ :))
