### ISSUE TITLE
Chức năng thông báo sau khi tải

### ISSUE THREAD

**Issue by namphanz** [lelinhtinh/Userscript#102]
Có tiếng bíp hoặc âm thanh nào đó sau khi tải xong
Thanks.

**Comment by lelinhtinh** [comment]
https://github.com/lelinhtinh/Userscript/blob/e1292e0880a32208ec657f760203db043eb6f6d4/manga_comic_downloader/manga_comic_downloader.user.js#L122

Tính năng này đã thêm vào nhưng mặc định không bật. Bạn sửa tham số `audioCues` để bật nhé:
```js
var audioCues = true;
```

**Comment by namphanz** [comment]
> https://github.com/lelinhtinh/Userscript/blob/e1292e0880a32208ec657f760203db043eb6f6d4/manga_comic_downloader/manga_comic_downloader.user.js#L122
> 
> Tính năng này đã thêm vào nhưng mặc định không bật. Bạn sửa tham số `audioCues` để bật nhé:
> 
> ```js
> var audioCues = true;
> ```

Cám ơn b rất nhiều. Xin lỗi tại mình diễn đạt không rõ. ý mình là muốn sau khi tải xong tất cả các chương thì thông báo 1 lần. ví dụ truyện có 30 chap, lần lượt tải từ chương 1, sau khi tải xong chương 30 thì nghe tiếng báo hoàn thành.
