### ISSUE TITLE
Đã 3 tháng kể từ lần cập nhật cuối :( #manga_comic_downloader

### ISSUE THREAD

**Issue by howcare1** [lelinhtinh/Userscript#104]
Hiện tại Hentaivn đã đổi tên miền , mình đã thử thay thế tất cả (Ctrl +H) từ Hentaivn.net thành Hentaivn.moe thấy script vẫn nhận diện dc trang web nhưng, các chức năng hoàn toàn không hoạt động :(. Mình cũng đã thử xài Violentmonkey và Tampermonkey nhưng mà vẫn không được. HentaiCube thì cũng không hoạt động luôn ạ, chỉ có vài trang web như lxhentai thì vẫn download dc. Hy vọng bác letinhlinh có thể sớm update. 
Chân thành cảm ơn bác.

**Comment by quyentruong** [comment]
Mình không biết trang Hentaivn.moe bị gì mà script không chạy được. Mình kiểm tra thử tất cả selector thì không có gì thay đổi. Mình thấy có 2 dòng này trong referer
```
'i02.hentaivn.net': 'https://hentaivn.net/',
'i1.hentaivn.net': 'https://hentaivn.net/',
```
Mình không biết key referer này lấy thế nào ?

**Comment by lelinhtinh** [comment]
> Mình không biết trang Hentaivn.moe bị gì mà script không chạy được. Mình kiểm tra thử tất cả selector thì không có gì thay đổi. Mình thấy có 2 dòng này trong referer
> ```
> 'i02.hentaivn.net': 'https://hentaivn.net/',
> 'i1.hentaivn.net': 'https://hentaivn.net/',
> ```
> Mình không biết key referer này lấy thế nào ?

Nó dựa vào location origin trong link ảnh (bao gồm subdomain), value của nó là link web gốc mà truyện hiển thị bình thường.

`referer` tự sinh ra khi truy cập web, nó sẽ là link của web vừa truy cập trước đó hoặc web hiện tại chứa ảnh.
Ví dụ khi đọc truyện thì `referer` sẽ là link chap hiện tại, nhưng nếu web cố tình kiểm tra thì thường chỉ kiểm tra domain chứ không làm chi tiết toàn link.

Một số web đăng lại, nhưng không muốn upload lại sẽ dùng một link proxy để vượt kiểm tra này, ví dụ: 
`https://example.com/proxy?url=https://i1.hentaivn.net/01.jpg`
Thường mình sẽ cắt bỏ luôn đoạn link proxy đằng trước nên origin của nó lại không phải là web hiện đang đăng truyện.
Trường hợp khác là do CDN, không trùng server với web chính, thậm chí có lúc domain cũng khác. Thường `referer` sẽ là web hiện tại luôn, nhưng do trường hợp 1 web dùng nhiều domain hoặc thay đổi nhiều lần thì cấu hình domain cũ vẫn hoạt động.

**Comment by quyentruong** [comment]
Khi mình view source của một trang truyện thì mình không thấy html phần list chapter, chỉ có javascript
```javascript
<script>
            var downx8874 = document.getElementById('inner-listshowchapter'); 
            var divx8874 = document.getElementById('ele-listshowchapter');

document.addEventListener("DOMContentLoaded", function () {
    var e = [].slice.call(document.querySelectorAll("div.lazy-listshowchapter"));
    if ("IntersectionObserver" in window) {
        let t = new IntersectionObserver(function (e, n) {
            e.forEach(function (e) {
                if (e.isIntersecting) {
divx8874.parentNode.removeChild(divx8874); 
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      document.getElementById("inner-listshowchapter").innerHTML = this.responseText;
    }
  };        
  xhttp.open("GET", "list-showchapter.php?idchapshow=29827&idlinkanime=thoi-mien-tuyet-doi-o-di-gioi", true);
  xhttp.send();
                }
            });
        });
        e.forEach(function (e) {
            t.observe(e);
        });
    }
});
</script>
```
Khi mà vô thử `https://hentaivn.moe/list-showchapter.php?idchapshow=29827&idlinkanime=thoi-mien-tuyet-doi-o-di-gioi` thì hiện ra được list chapter trong view source.
Mình nghĩ cần viết custom function để lấy list chapter

**Comment by lelinhtinh** [comment]
Fixed by #107 #108
