### ISSUE TITLE
lỗi tải không đủ chương ( truyenfull) và không có tiêu đề  chương bên (truyenyy)

### ISSUE THREAD

**Issue by chung19** [lelinhtinh/Userscript#124]
1 số truyện bên truyenfull bị lỗi tải được khoảng 10% chương là tự lưu thành file epub ( có thể do thời gian tải chương kế tiếp nhanh quá ) bên truyenyy.vip tải bị thiếu tên của chương truyện
 vd : 
https://truyenmoii.com/trong-sinh-tu-tien-tai-do-thi
https://truyenyy.vip/truyen/quan-huu-van/
hi vọng tác giả sẽ fix lại cảm ơn nhiều !

**Comment by chung19** [comment]
@

**Comment by chung19** [comment]
tác giả có thắc mắc gì phản hồi lại giúp mình nhé

**Comment by chung19** [comment]
update xin lỗi tác @lelinhtinh nhé lỗi bên truyenfull bi lỗi 2 chương 147 148 nên không tải được , tác có thể thêm tùy chọn bỏ quả 1 số chương( tích bọn chương cần bỏ thủ công) để tránh như này trong thời gian sắp tới không . còn bên truyenyy.vip chưa thấy fix được lỗi tải truyện mà không thấy có tiêu đề chương chờ tác xem xét

**Comment by lelinhtinh** [comment]
@chung19 trong script truyenfull mình vẫn ghi chương lỗi khi bị thiếu nội dung, còn trường hợp bị ép tải xuống là do lỗi mạng. 
https://github.com/lelinhtinh/Userscript/blob/4784f4239a5dbb85e8290754c8a2bfa015a0e077/truyenFull_downloader/truyenFull_downloader.user.js#L55-L65
Đoạn code trên là tăng dần thời gian chờ giữa những lượt tải truyện, để phòng trường hợp server giới hạn truy cập (rate limiting), tối đa là 700ms. Bạn thử tăng giới hạn này lên 1000, nếu vẫn không được thì tìm cách khác, vì nếu tăng quá nhiều thì thời gian tải truyện rất chậm.

**Comment by chung19** [comment]
@lelinhtinh cái bên truyenfull là do lỗi chương ý 2 chương không xem được đó ý mình là bạn có thể update code khi tải mà gặp lỗi chương set time out vẫn không tải được thì tự động bỏ qua  chương đó ( thêm 1 cái tiêu đề báo lỗi vào chương lỗi) xong thì tải tiếp còn script hiện tải nó gặp lỗi như này sẽ hiện màu đỏ err xong lưu  luôn từ chương lỗi thành file epub ( k tải chương kế tiếp chương bị lỗi nữa)

**Comment by chung19** [comment]
@lelinhtinh với kiểm tra giúp mình cái script bên truyenyy.vip xem  mình  tải ok mà nó không lấy tiêu đề chỉ để chương 1 2 3 chứ không có tittle vd cái này nè https://truyenyy.vip/truyen/quan-huu-van/

**Comment by lelinhtinh** [comment]
> @lelinhtinh với kiểm tra giúp mình cái script bên truyenyy.vip xem  mình  tải ok mà nó không lấy tiêu đề chỉ để chương 1 2 3 chứ không có tittle vd cái này nè https://truyenyy.vip/truyen/quan-huu-van/ 
> ![image](https://user-images.githubusercontent.com/98091082/184489452-718ef2c5-a180-4e4c-825b-85c5d62ca56d.png)
> 

Cái này fix rồi, bạn cập nhật bản mới chưa?

**Comment by chung19** [comment]
@lelinhtinh  ok r cảm ơn bạn  , mới update hay sao á trước có cập nhập là cái tampermonkey nó báo ngay mà
