### ISSUE TITLE
Download không thành công truyện từ nguồn truyenvnpro

### ISSUE THREAD

**Issue by tienok2004** [lelinhtinh/Userscript#130]
Mình down truyện từ nguồn truyenvnpro.com (trước là truyenvn.vip nhưng do đổi tên miền nên mình update lại script) thì thành công được 157 chap (tổng cộng 169 chap) nhưng 10 chap cuối thì down kiểu gì cũng bị error mặc dù mở lên vẫn xem chap bình thường.

Nhờ bạn kiểm tra giúp mình.

Link truyện: https://truyenvnpro.com/tan-the-gioi-moi-wonderful-new-world

screenshots: 

![image](https://user-images.githubusercontent.com/68675946/205477692-36a93b5d-40b3-44f9-97bc-e99d3a74f66e.png)

**Comment by lelinhtinh** [comment]
Chắc do server lag thôi, mình không thấy có gì lạ, thậm chí kiểu tải ảnh bằng ajax cũ họ cũng bỏ luôn rồi. https://github.com/lelinhtinh/Userscript/commit/b1c3b4f65ddb361fe1a5d25adf8b8ddbc50edec0

**Comment by tienok2004** [comment]
Hôm nay mình thử down lại thì ok rồi nhưng  khi nhấn alt + Y down toàn bộ thì lại down mỗi chap 2 lần (như trong hình). :(

![image](https://user-images.githubusercontent.com/68675946/205542597-494d5d08-2ddb-484c-9ea6-bb266b71bd51.png)

**Comment by tienok2004** [comment]
à vậy mỗi lần update lại tên miền thì mình chỉ cần sửa chỗ nào có truyenvnpro thành tên miền mới là chạy được đúng không bác? Có cần chỉnh chỗ nào nữa không?

**Comment by lelinhtinh** [comment]
Nếu họ không sửa gì thì vậy, còn lại tùy tình huống. Đơn giản nhất thì chỉ cần sửa domain, đôi lúc thêm selector. Trường hợp phiền phức hơn như ảnh bị mã hóa, tải chậm bằng ajax, ... thì phải viết function riêng để lấy ảnh.

**Comment by tienok2004** [comment]
> 

ok cảm ơn bác nhiều
