### ISSUE TITLE
có thể cập nhật link mỗi khi các trang đổi tên miền được k ạ

### ISSUE THREAD

**Issue by aphuong2k** [lelinhtinh/Userscript#138]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (name + version):**
- Script: [e.g. Anti Social Locker 1.1.4]
- UserScript manager: [e.g. Violentmonkey 2.12.7]
- Browser: [e.g. Google Chrome  86.0.4240.183]

**Comment by lelinhtinh** [comment]
Nếu chỉ đổi tên miền thì có 3 chỗ cần cập nhật

	// @version         3.3.14

Tăng số phiên bản lên, ví dụ `3.3.15`

Thêm tên miền mới bằng `@match`, quy tắc chi tiết xem [tại đây](https://violentmonkey.github.io/api/matching/). Ví dụ:

	// @match           http://*.blogtruyen.xxx/*

Tìm code tương ứng, thêm một dòng `case` với tên miền mới. Ví dụ:

	case 'blogtruyen.xxx':
