### ISSUE TITLE
Cập nhật thêm truyenmoi-org và các web mới được không bạn ơi

### ISSUE THREAD

**Issue by gozvn** [lelinhtinh/Userscript#145]
Xin hỏi là pj này đã bị ngưng chưa bạn.
Có thể cập nhật một số web truyện mới được không bạn ?

**Comment by gozvn** [comment]
Mình hay dùng script của bạn để tải epub. Không biết có cá nhân không nhưng cũng mong bạn update script này.

**Comment by lelinhtinh** [comment]
Không làm đâu, lười lắm. Trước giờ làm script thì cũng tải gần trăm bộ rồi, đọc chục năm nữa chưa hết.
