### ISSUE TITLE
Lỗi down ảnh ở 10download.com

### ISSUE THREAD

**Issue by lbpth** [lelinhtinh/Userscript#150]
**Describe the bug**
Bấm vào chỉ down về file 4KB, ko xem được ko mở được ảnh
**To Reproduce**
1. Go to '...' vào trang 110download
2. Click on '....' chọn ảnh rồi bấm chuột trái
3. Scroll down to '....' Ảnh lưu về máy
4. See error - ko mở được, file kích thước cũng chỉ có 4KB, chắc chắn lỗi

**Expected behavior**

**Screenshots**

**Context (name + version):**
- Script: [e.g. Anti Social Locker 1.1.4]
- UserScript manager: [e.g. Violentmonkey 2.12.7]
- Browser: [e.g. Google Chrome  86.0.4240.183]

**Comment by lelinhtinh** [comment]
Ý bạn là trang này <http://10wallpaper.com>? Mình vẫn tải bình thường.
