### ISSUE TITLE
Bị chặn download

### ISSUE THREAD

**Issue by duongtuanvn** [lelinhtinh/Userscript#156]
Khi vào tài truyện thì bị lỗi chặn rồi ạ

![image](https://github.com/lelinhtinh/Userscript/assets/74706829/50ff83c8-cd13-483d-92d8-fb45782b4178)

**Comment by lelinhtinh** [comment]
Bạn chưa kích hoạt extension.

![image](https://github.com/lelinhtinh/Userscript/assets/5460915/555d7038-9b57-4353-a82c-596cd1275077)

Bật nó lên và tải lại trang.
