### ISSUE TITLE
TruyenYY, TruyenFull, TruyenCV downloaders only work with Greasemonkey 4 on Firefox

### ISSUE THREAD

**Issue by lelinhtinh** [lelinhtinh/Userscript#24]
I don't know why...

**Comment by gianghd** [comment]
Mình dùng firefox + GM4 để tải chương về thì thấy có mấy điểm như sau:
1. Size file lớn hơn bình thường gấp 4 lần (ngày trc mình hay dùng chrome + tampermonkey).
2. Mở 1 file 1000 chương trên FBReader ngày trc bấm phát ăn ngay. Bây giờ thì phải chờ khoảng 2 phút mới load xong.

**Comment by lelinhtinh** [comment]
Mình đã nén template bên thư viện [jEpub](https://github.com/lelinhtinh/jEpub/commit/e01aa5e6f414abd7d754aa85f660557b78b5e7d3) nhưng còn đang thử nghiệm, sẽ cập nhật vào script tải truyện sau.
Tuy vậy khả năng nén của nó vẫn sẽ ít hơn thư viện **js-epub-maker** trước đây do cách thiết kế khác nhau. Ví dụ có 1000 chương thì **jEpub** sẽ tạo ra 1000 file chương truyện, còn **js-epub-maker** chỉ gom vào 1 file.
Tùy theo cách đọc epub của phần mềm reader, có thể **jEpub** sẽ chậm hơn nếu reader thực hiện import thay vì đọc trực tiếp, khi đó nó sẽ cần index và vaild từng file.

**Comment by lelinhtinh** [comment]
@gianghd bạn cập nhật phiên bản mới nhé, sẽ giảm được file size kha khá đấy.

**Comment by LearKing317** [comment]
Từ 4.0 trở lên bị lỗi hết , mình sài google chrome , 4.0 trở lên nén ebook không ra , 4.2.1 thì 99% đứng click lần 2 cũng không xuất hiện ngắt tải để xuất ebook . 4.3 thì để cái chữ nén ebook mà trong khi test có 2 chương mà hơn chục phút không thấy cái file ebook nó xuất ra

**Comment by lelinhtinh** [comment]
Lỗi này ngớ ngẩn thật, đúng là do `GM_xmlhttpRequest` không hỗ trợ async, nhưng mấy script này đâu có cần dùng đến `GM_xmlhttpRequest` 😂

**Comment by dragonlord4747** [comment]
Mấy bác cho em hỏi với. Truyenyy giờ có cái công nghệ chống copy của chương vip, kiểu nó tự chèn 1 thẻ html vào content. Các bác ai biết công nghệ kiểu đó keysearch là gì ko ạ???

**Comment by lelinhtinh** [comment]
Thường thì đọc được sẽ copy được.

- Khó nhất là kiểu render text thành image, dù vậy với công nghệ OCR hiện tại cũng lấy được khá nhiều nội dung. Hơn nữa lưu image sẽ ngốn thêm bandwidth và không responsive được, nên sẽ ít web muốn dùng cách này.
- Ẩn một số từ, dùng css content để hiển thị. Cách này khi copy mà không để ý sẽ bị thiếu nội dung, nhưng vẫn có cách tải được. Chèn thẻ HTML bạn nói có thể là cách này, mình không có acc VIP nên không kiểm tra được. Nếu đúng là nó thì nội dung sẽ nằm trong attribute của thẻ đó, hoặc nếu họ dùng class thì sẽ có một thẻ style chứa content cho class đấy.
- Các kiểu chặn khác bằng JavaScript khác như disable text selection, override copy, ... thì rất dễ vượt qua.
