### ISSUE TITLE
TruyenCV tải đến chương lỗi thì dừng lại ko thao tác tiếp được

### ISSUE THREAD

**Issue by gianghd** [lelinhtinh/Userscript#25]
Trình duyệt: Chrome
Truyện: http://truyencv.com/thua-ke-hai-ngan-ti-trillion/
Cứ tải đến chương 556 thì dừng lại không xử lý tiếp. Cũng không export epub được.

**Comment by lelinhtinh** [comment]
Chương 556 xem cấu trúc không lỗi gì, để mình xem lại.

Từ version 4+ thì mấy script tải truyện chữ của mình chỉ chạy được trên **Firefox** qua add-on [Greasemonkey](https://addons.mozilla.org/vi/firefox/addon/greasemonkey/), còn trình duyệt khác và add-on khác sẽ không export epub được. #24 
Lỗi này là do mình chuyển sang thư viện [jEpub](https://github.com/lelinhtinh/jEpub) mình vừa viết, bản thân nó thì không lỗi nhưng có lẽ mấy add-on khác dùng GM API cũ nên không xử lý được Promise.

**Comment by lelinhtinh** [comment]
Lỗi bị thiếu tiêu đề.
```html
<div class="header">
    <h2 class="title"> </h2>
</div>
```
Mình có viết 1 bộ lọc tên chương trong nội dung, vì nếu không sẽ bị hiển thị tên chương 2 lần như trong [Chương 556](http://truyencv.com/thua-ke-hai-ngan-ti-trillion/chuong-556/). Trong truyện này thì tên chương thậm chí còn bị đặt sai.
Giờ phải xử lý vụ này sao đây, tiếp tục lọc tên chương trong nội dung hay bỏ qua, và khi thiếu tên chương thì ghi gì vào đó?

**Comment by gianghd** [comment]
Không có tên Chương thì cứ để default là "Chương x" hoặc "không có tên chương" chẳng hạn.

**Comment by lelinhtinh** [comment]
Đã làm rồi kiểu "Chương x", bạn cập nhật phiên bản mới nhé.
Ah lưu ý là chỉ chạy được trên **Firefox** qua add-on [Greasemonkey](https://addons.mozilla.org/vi/firefox/addon/greasemonkey/).

**Comment by lelinhtinh** [comment]
Hiện tại đã hoạt động tốt trên **Tampermonkey** và **Violentmonkey**.
