### ISSUE TITLE
About new style css

### ISSUE THREAD

**Issue by huntermad** [lelinhtinh/Userscript#26]
Truyenyy có dùng code tạo epub khác Truyencv va truyenfull không hả and Baivong? Hay là do code trình duyệt của từng trang?

DO thấy code trong body của nó là

<   p class="indent">Hơn nữa là với hoàn cảnh của Trấn Long Uyên này, sơ ý một chút để cho Nội Tinh Lô nổ, dẫn phát loạn lưu sát khí cùng nhau bạo phát, tất cả mọi người tại đây cũng không có người nào có thể sống khá giả.<   /p   >----

Còn 2 cái kia là kiểu này 

"Móa nó, lão tử đang làm gì đường đường nam nhi bảy thuớc, tại sao có thể theo người một nhà vận dụng tà niệm... Bất quá cảm giác như vậy, ta vậy mới không tin nàng sẽ không có cảm giác..." <  br/>< 
  br/>----**

**Comment by lelinhtinh** [comment]
Cùng sử dụng thư viện [jEpub](https://github.com/lelinhtinh/jEpub), do truyenyy nạp nội dung theo từng dòng trong chương nên tạo ra cấu trúc đó, còn 2 trang truyencv và truyenfull nạp nguyên nội dung chương.

**Comment by huntermad** [comment]
Anh activate cái account trang này đc ko?
http://zzbaivong.forumvi.com/

Đưa lên 1 số cách sửa chửa nhanh.

**Comment by lelinhtinh** [comment]
Trang đó không phải của mình tạo. Để mình mở lại **Devs Forumvi**.

**Comment by huntermad** [comment]
Ừm, Trong cái thư viện Jepub thì anh có chỉnh lại đc phông cho file epub tạo ra đc ko?

Mấy cái title dung phông to quá. Với lại dùng Serif cho body hơi khó nhìn còn Palatino cho title thì "ươ" nhìn hơi xấu với to quá.

**Comment by lelinhtinh** [comment]
Về font thì bạn có thể chỉnh trong trình đọc sách theo sở thích. Mình sẽ tìm thử font mà không dính bản quyền rồi thêm vào sau.

**Comment by gianghd** [comment]
Có cách nào gộp chung 1 file htm không? Đang tách ra load để đọc chậm quá.

**Comment by lelinhtinh** [comment]
Nếu vậy thì để mình thêm tùy chọn gộp file cho ai cần.
Mà mình thấy **jEpub** load nhanh hơn, ngay cả trên con Lumia cũ của mình cũng đọc ngon lành. Còn bản cũ, dùng thư viện **js-epub-maker** thì phải dùng Calibre convert lại mới đọc được, lại còn lỗi mục lục.

**Comment by huntermad** [comment]
Do phiên bản cũ nó gộp lại thành 1 file content.xhtml to đùng mỗi lần mở ra là nó load toàn bộ cái đó luôn còn giờ thì chia ra từng chương chỉ load 1 chương 1 lần thôi.

Có lẽ bạn đó xài bản cũ chứ ko thể nào load chậm hơn bản cũ đc.

**Comment by lelinhtinh** [comment]
Tạm bỏ qua việc gộp nội dung vào 1 file, vì phải thay đổi mã nguồn khá nhiều.
@gianghd Bạn cho mình thông tin về trình đọc ebook và hệ điều hành bị chậm khi dùng phiên bản mới này, mình kiểm tra lại xem.

**Comment by gianghd** [comment]
Mình dùng FBReader version 0.12.10.
Win7 32bit.

Trước 1 truyện tầm 1500 chương mở 15s là xong.
Bây giờ 1000 chương mở hơn 1phut

**Comment by huntermad** [comment]
Mở bằng Sigil thì thấy nó là gộp chung hay là chia ra?

**Comment by lelinhtinh** [comment]
@gianghd 2 trình đọc ebook này quá chậm, FBReader đã ngừng phát triển bản Windows từ lâu, bản Linux còn nhanh hơn nhiều. Sigil thì quá tệ, chia cây thư mục thừa thải, còn không có chức năng chuyển chương khi đọc đến cuối.

Mình xin gợi ý một số trình đọc khác:

1. [ePubViewer](http://geek1011.github.io/ePubViewer/): Đọc trực tiếp EPUB trên trình duyệt.
2. [Mobipocket Reader Desktop](https://download.com.vn/mobipocket-reader-desktop/download) _(nên dùng)_:  Khi mở file EPUB nó sẽ tự động convert sang PRC, tốn chút thời gian, có thể lỗi ký tự mục lục, nhưng khi mở và đọc cực nhanh.
3.  [SumatraPDF](https://www.sumatrapdfreader.org/download-free-pdf-viewer.html): Một trình đọc PDF rất nhẹ, có hỗ trợ EPUB và nhiều định dạng khác. Bạn cần cài đặt **Menu > Setting > Advanced Option**, tìm phần `EbookUI` và sửa lại `FontName` để không bị lỗi Tiếng Việt, ví dụ:
```
EbookUI [
	FontName = sans-serif
	FontSize = 16
	TextColor = #5f4b32
	BackgroundColor = #fbf0d9
	UseFixedPageUI = false
]
```
4. [Calibre](https://calibre-ebook.com/download_windows): Đọc hơi chậm, nhưng ít ra nhanh hơn 2 cái kia. Có thể chuyển đổi định dạng ebook.
5. [Kindle PC](https://www.amazon.com/kindlepcdownload/ref=klp_hz_win): Đọc nhanh, giao diện đẹp nhưng yêu cầu tài khoản amazon, không đọc trực tiếp epub được. Bạn cần dùng Calibre để convert sang dạng MOBI hoặc PRC, sau đó chép vào thư mục **Documents > My Kindle Content**.

**Comment by lelinhtinh** [comment]
@huntermad về phần font cho nội dung thì Open Sans được không nhỉ? https://github.com/lelinhtinh/jEpub/issues/1

**Comment by huntermad** [comment]
Kinh nghiệm của ta:

FBReader giờ còn xài làm gì? Dev chuyển qua làm mobile app mấy năm rồi. Với lại giao diện xấu, đọc khó chịu

Sigil thì để edit thôi. Nó load cả structure ra để mình edit nên lâu lắm.

Epubviewer chỉ đọc tốt mấy epub nhẹ thôi, epub nặng xài reader cho nhanh.

Mobipocket reader mở rất nhanh nhưng giao diện lỗi thời với ít tùy chỉnh quá rồi ko còn phát triển nữa. Ta trước kia là đọc chủ yếu đọc Prc vơi mobi nhưng chuyển qua epub thì 1 đi ko trở lại.

SumatraPDF: rất đa năng, ngoài PDF thì còn đọc được file khác như cbz(cần chỉnh chút với ko hỗ trợ chuyển file... nếu ko là số dách rồi!!!) và đặc biệt là epub. Nói chung là nếu đã sửa đc với cách trên thì đọc tốt. Có đều là tùy chọn gần như ko có. Lựa chọn tốt nhất cho máy yếu

Epub reader của Calibre thì tốc độ vừa nhưng mà đối lập với Sumatra thì đủ các tùy chọn rồi còn có thể thế css vào để thay css của epub nữa. Máy đủ mạnh thì xài Epub reader tốt hơn so với Sumatra.

Kindle Pc: chưa thử bao giờ.


ĐỔI FONT: ko biết.
Muốn đổi font thì convert lại bằng calibre để nó chuyển jackson.css về css chuẩn của calibre để chỉnh bằng Sigil hay cách giải nén. Chỉnh luôn từ jackson.css thì chỉ có người trình độ về code mới hiểu đc cái rừng đó.
Chuyển về font nào trong máy của bạn cũng được. Thay tên vào thôi

**Comment by lelinhtinh** [comment]
Mobipocket Reader thấy giao diện cũng ổn mà.

![Mobipocket Reader](https://user-images.githubusercontent.com/5460915/40468396-836464d6-5f57-11e8-9991-e30d3c6e70e8.png)

**Comment by huntermad** [comment]
1. Ko biết code nào để thêm indent cho prc/mobi---> khó đọc
2. Như ở trên, ko biết cách nào để chỉnh khoảng cách giữa các đoạn---> khó đọc 
3. Giao diện kiểu cũ, ngay cả khi fullscreen vẫn có mấy cái bar ở 3 bên. 
4. Ngoài ra còn tiện ích của epub nữa, epub có thể mở toc ngay bên cạnh để biết ngay đang ở chương nào và chuyển chương. Mobipocket thì phải nhấn về phần mục lục ban đầu rồi tự chuyển tới chương muốn mở.
5. Thiếu  tùy chỉnh.

**Comment by huntermad** [comment]
Dùng Online converter như Zamzar vẫn được. Tuy cỡ hơn 2k chương thì hình như hơi quá nhưng làm thử với cõ 1,5k chương thì OK.

Nếu trước đó convert qua epub bằng calibre thì nó theo định dạng sẵn rồi, 2300+ chương convert vô tư nhưng thế thì convert ngay bằng calibre cho rồi
