### ISSUE TITLE
When you get a moment...

### ISSUE THREAD

**Issue by Martii** [lelinhtinh/Userscript#27]
Your google auth is corrupted on OUJS. I've removed the corruption but I need you to check to make sure you can log in with that hash e.g. I kept the newest looking one.

Please let me know if it's working for you. If not I can restore the first hash.

Thanks,
OUJS Admin

**Comment by lelinhtinh** [comment]
Work for me. I can log in via Google Auth.
Thank @Martii for the announcement.

**Comment by Martii** [comment]
Glad it works for you.. you are 2nd person that this happened to... guess I'm getting better at guessing which hash to choose. ;)

Thanks again.

**Comment by Martii** [comment]
Oh wait... just noticed you have two facebook auths. :\

**Comment by Martii** [comment]
Hang on while i dump the first hash for that and if you could recheck I'd appreciate it... give me a about 10 minutes.

**Comment by Martii** [comment]
Okay... it's done... good news for that?

**Comment by Martii** [comment]
I'll take that thumbs up and the switch in the array as a success. Thanks and sorry to bother you... the way the code works is it picks the first one and those are the ones I removed... so I'm guessing both your FB and Goo were unusable. This bug was pre me and it usually only affects accounts around 2014.

Anyhow... looks good over here. :smile_cat:

**Comment by lelinhtinh** [comment]
It's working at the moment. Thank for your work.

**Comment by Martii** [comment]
No problem. Thanks for the continued support on OUJS. We're glad to have you. :)
