### ISSUE TITLE
Anti Social Locker Missing JQuery

### ISSUE THREAD

**Issue by neoOpus** [lelinhtinh/Userscript#29]
I think your script miss this line

// @require     https://code.jquery.com/jquery-3.2.1.min.js

so it's not working

**Comment by lelinhtinh** [comment]
Thank you, I checked it. That is necessary for [Greasemonkey 4.0+](https://wiki.greasespot.net/index.php?title=%40grant&type=revision&diff=7546&oldid=7438).
Previously, this was not a problem. **Anti Social Locker** uses `@grant none`. In this mode, the sandbox is disabled and the script will run directly at the page context. Therefore, it will be possible to use jQuery in the global variable of web page.
Can you send me a Pull requests?
