### ISSUE TITLE
Thêm ảnh bìa vào epub của các trang truyện

### ISSUE THREAD

**Issue by fivegins** [lelinhtinh/Userscript#33]
khi đọc trên các ứng dụng di động có thêm cái ảnh bìa để dễ phân biệt giữa các truyện nữa. mình hy vọng bổ xung thêm cái cover của epub vào trang truyencv downloader, truỳenull, truyenyy. cảm ơn 🍡

**Comment by lelinhtinh** [comment]
Những script này mình đều có để sẵn mục `ebookCover` nhưng tạm ẩn đi vì vài lý do như:

- Ảnh cover quá nhỏ ở nhiều truyện.
- Sự không tương thích giữa API `GM_xmlhttpRequest` cũ và `GM.xmlHttpRequest` mới.
- Yêu cầu `@connect  *` trên Tampermonkey sẽ hiện cảnh báo dễ gây hiểu lầm cho người dùng.

Còn gần đây thì Tampermonkey gặp lỗi `Limited runtime host permissions`, nhưng vừa thử thấy đã hoạt động lại bình thường, chỉ là còn cảnh báo thôi.

Tóm lại thì vẫn sẽ thêm cover vào epub được, mình sẽ bổ sung sớm thôi. 😋

**Comment by fivegins** [comment]
:smiley: ừm mình nghĩ ảnh nhỏ thì không ảnh hưởng nhiều đâu. ngày nay đọc ebook chủ yếu thiết bị di động mà cái ảnh bìa tác dụng của nó mình nghĩ là để phân biệt cho dễ nhìn ở thư viện offline dạng như này [https://lh3.googleusercontent.com/rGL9HJelWGmPMlBgPNg-tLYW3KqTHVN-cYgD3FfpY4l3kv8L_u-OgqJXI4RZHY3PX3Jl=w1366-h657-rw](https://lh3.googleusercontent.com/rGL9HJelWGmPMlBgPNg-tLYW3KqTHVN-cYgD3FfpY4l3kv8L_u-OgqJXI4RZHY3PX3Jl=w1366-h657-rw) thực sự không có cái bìa mò mò từng truyện cũng khó

**Comment by lelinhtinh** [comment]
Tạm thời bạn dùng [Calibre](https://calibre-ebook.com/download) để thêm cover thủ công nhé.
