### ISSUE TITLE
Hy vọng tác giả thêm tạo epub từ wattpad

### ISSUE THREAD

**Issue by helloh5n1** [lelinhtinh/Userscript#41]
VN mình chuộng wattpad lắm và cũng nhiều truyện hay có trên đó, nếu làm đc hy vọng tác giả thêm trang này thì tốt quá 💯 mình thấy có trang này mà xem không hiểu có trang của tác tìm tòi google là biết làm theo :3 https://github.com/GatoLoko/Wattpad2Epub

**Comment by lelinhtinh** [comment]
Ứng dụng đó viết bằng Python, mình cài thử thấy vẫn hoạt động, bạn lấy dùng luôn cũng được đấy.

Ps: Có truyện dài tầm 70 chương mà tải mới 43 đã bị lỗi 404, trong khi thực tế chương đó vẫn đọc được. Không biết lỗi này do ứng dụng hay bị Wattpad chặn.

**Comment by lelinhtinh** [comment]
Có vẻ là Wattpad chặn, đưa ra cảnh báo giả https://github.com/GatoLoko/Wattpad2Epub/issues/10

**Comment by nntoan** [comment]
Chắc là cần fake UserAgent.
