### ISSUE TITLE
nhentai downloader button no completion at end

### ISSUE THREAD

**Issue by fabmind** [lelinhtinh/Userscript#42]
Hello,
oN some page on nhentai the button dont do the completion at end.
thx
(nice job)

**Comment by lelinhtinh** [comment]
Could you give me some sample links?

**Comment by fabmind** [comment]
EX/
https://nhentai.net/g/31/
In fact it takes very long to have green button after completion (15-20 min)

**Comment by lelinhtinh** [comment]
After downloading all images, the script will start compressing them to the CBZ file. This process depends on the number of images and computer hardware. My computer was completed in 20 seconds with this comic (174 photos) and 3 seconds for short comics (~ 20 photos).
I don't think this is a bug. Moreover, the compression process performed by 3rd party library is [JSZip](https://github.com/Stuk/jszip).

**Comment by fabmind** [comment]
ok it seems the process do a pause if you change tabs. i have to rest on it to finish the process (20-30sec)

**Comment by lelinhtinh** [comment]
If the cause is due to unfocus tab, you can open each comic in a new window.
