### ISSUE TITLE
Không nén truyện được sau khi tải trên truyenyy

### ISSUE THREAD

**Issue by trungdoan2507** [lelinhtinh/Userscript#44]
Sau khi tải truyện xong chỉ báo "ĐANG NÉN EBOOK" mãi

**Comment by lelinhtinh** [comment]
Mình thử tải vài truyện ngắn vẫn tốt, bạn gửi cho mình link truyện bị lỗi đó được không? Và thêm thông tin về trình duyệt và tiện ích quản lý mà bạn dùng, ví dụ: Google Chrome 74.0.3729.169, ViolentMonkey 2.10.5

Có thể do truyện quá dài nên tốn nhiều thời gian để nén hơn bình thường. Trình duyệt thường sẽ giảm hiệu suất ở những tab không sử dụng, nên để tải không bị chậm, bạn nên mở cửa sổ riêng cho mỗi truyện đang tải.

**Comment by trungdoan2507** [comment]
Mình đã test thử và phát hiện lỗi xảy ra khi dùng Tampermonkey 4.8.41. Mình chuyển sang dùng ViolentMonkey thì tải truyện bình thường

**Comment by lelinhtinh** [comment]
Hiện tại Tampermonkey còn có thêm lỗi không tải được cover #45. Nhưng lỗi này đã được fix trong bản Tampermonkey Beta.
