### ISSUE TITLE
Lỗi tải truyện Tsugumomo (chap 87) tại NetTruyen

### ISSUE THREAD

**Issue by namck2999** [lelinhtinh/Userscript#54]
[Tsugumomo_Chương_87.zip](https://github.com/lelinhtinh/Userscript/files/3621372/Tsugumomo_Ch.ng_87.zip)

**Comment by lelinhtinh** [comment]
Lỗi này tương tự #40, do cuối link ảnh có kèm `id`.

Lỗi khác:
- Lỗi credit đầu chương _(không ảnh hưởng nội dung)_: 55, 57, 57-2.
- Lỗi ảnh từ blogspot _(chắc bị Google ban)_: 28, 38, 39, 63, 65.

Các lỗi này khi đọc truyện thì không thấy do NetTruyen có link ảnh dự phòng để thay thế khi ảnh chính bị lỗi. Có lẽ mình sẽ lọc lấy link `data-cdn` làm mặc định.
