### ISSUE TITLE
Tải truyện chữ tổng hợp

### ISSUE THREAD

**Issue by lelinhtinh** [lelinhtinh/Userscript#58]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2420%20Funded-%2300A156.svg" />](https://issuehunt.io/r/lelinhtinh/Userscript/issues/58)

- [ ] truyencv.com
- [ ] truyenyy.com
- [ ] truyenfull.vn
- [ ] truyenvkl.com #56
- [ ] bachngocsach.com/reader
- [ ] metruyenchu.com
- [ ] vtruyen.com
- [ ] nuhiep.com

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- $20.00 have been anonymously funded.

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/lelinhtinh/Userscript/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by nntoan** [comment]
Cái truyenvkl.com không support được đâu. Nó bật full security của CloudFlare, request nào cũng bắt về cái đoạn redirect.

Còn mấy site kia nếu bạn cho dùng chung tên thì tớ convert về dùng với [mbDownloader](https://github.com/nntoan/mbDownloader) cho :)

**Comment by lelinhtinh** [comment]
Trang truyenvkl mình vừa thử thấy vẫn tải bình thường mà, cùng lắm thì thêm referrer vào thôi.
Mấy site kia mình có làm rồi, dự là sau này làm script tổng hợp thì bỏ chứ làm chi thêm nữa.

**Comment by vovilangtu** [comment]
Trang http://sangtacviet.tk/ có làm được không bạn?

**Comment by lelinhtinh** [comment]
> Trang http://sangtacviet.tk/ có làm được không bạn?

Theo lý thuyết là được, nhưng nó nằm ngoài tiến trình hiện tại, mình sẽ lưu ý trang này để cấu trúc script cho phù hợp.

**Comment by vovilangtu** [comment]
Cảm ơn!

**Comment by hianalyst** [comment]
bác có thể làm thêm trang bạch ngọc sách không ạ :P chất lượng dịch bên đó đỉnh quá, truyện yy copy truyện kiếm vương triều theo kiểu treo đầu dê bán thịt chó, đang đọc dịch hay cái chắp vá thêm vc vào làm hụt hẫng quá

**Comment by lelinhtinh** [comment]
@hianalyst có sẵn [BachNgocSach downloader](https://greasyfork.org/vi/scripts/388352-bachngocsach-downloader) do @nntoan làm đó bạn.

**Comment by hianalyst** [comment]
ư ư, cảm ơn bác nhiều nhiều <3
h em mới biết

**Comment by mrtk0y** [comment]
xịn quá anh oiWIII <3

**Comment by nghia9a5** [comment]
bác ơi truyenFull_downloader không xài được nữa, bác check lại xem giúp em nhé

**Comment by lelinhtinh** [comment]
> bác ơi truyenFull_downloader không xài được nữa, bác check lại xem giúp em nhé

Họ đổi domain sang `.net`, bạn cập nhật phiên bản [4.6.4+](https://greasyfork.org/vi/scripts/28718-truyenfull-downloader) nhé.

**Comment by hianalyst** [comment]
> * [ ]  [truyencv.com](http://truyencv.com)
> * [ ]  [truyenyy.com](http://truyenyy.com)
> * [ ]  [truyenfull.vn](http://truyenfull.vn)
> * [ ]  [truyenvkl.com](http://truyenvkl.com) #56
> * [ ]  [bachngocsach.com/reader](http://bachngocsach.com/reader)

bác ơi, cái bachngocsach bị lỗi rồi :( bác fix lại dc k ạ
![Screenshot_2](https://user-images.githubusercontent.com/34888554/79830870-8372da80-83d0-11ea-8d88-b789117b3344.png)

**Comment by thejack99** [comment]
truyenyy download chuong VIP bi loi "Dang Tai Noi Dung Vip" fix lai gium voi.

**Comment by erispro** [comment]
tải bên yy toàn lỗi cách dòng admin ơi 
![image](https://user-images.githubusercontent.com/69828779/90459983-6a660600-e0f2-11ea-836f-8e8d44e50fef.png)

**Comment by nghia9a5** [comment]
https://bachngocsach.com/reader/ 
trên bachngocsach cũng không nén được epub, bác fix lại cho anh em đồng đạo với. cám ơn bác nhiều

**Comment by hianalyst** [comment]
> https://bachngocsach.com/reader/
> trên bachngocsach cũng không nén được epub, bác fix lại cho anh em đồng đạo với. cám ơn bác nhiều

hy vọng bác ấy fix cho :D
chất lượng dịch ở bns thuộc dạng đỉnh nhất vn mình luôn rồi 👯‍♀️

**Comment by tienok2004** [comment]
hóng bản metruyenchu.com quá. tool quá chất lượng :D

**Comment by nntoan** [comment]
> > https://bachngocsach.com/reader/
> > trên bachngocsach cũng không nén được epub, bác fix lại cho anh em đồng đạo với. cám ơn bác nhiều
> 
> hy vọng bác ấy fix cho :D
> chất lượng dịch ở bns thuộc dạng đỉnh nhất vn mình luôn rồi 👯‍♀️

Hehe, bác có issue gì với BNS Downloader bác chạy qua đây raise issue giúp mềnh nhé: https://github.com/nntoan/UserScripts. Không hứa hẹn fix nhanh những sẽ fix vì mình cũng khá bận :D 

Vụ metruyenchu.com thì mình cũng đang quẩy rồi nhưng thằng này cũng hơi khoai thị sắn đấy vì nó sign với JWT, dịch ngược về mã gốc rồi nhưng có vẻ ko ăn thua. Đây là cách nó tạo signature với JWT.

ví dụ đây là URL để lấy chương của nó

```
https://api.truyen.onl/v2/chapters?book_id=100614&sign=eyJpdiI6ImFCNlNocEJ1XC9INlwvMUdYUHV5NGZUQT09IiwidmFsdWUiOiJ5SVY5SFgrd3UwR1JpYWFyZ3NhajZRPT0iLCJtYWMiOiI3NGFlNzNiYjUwZTM5YzE0MDM1NjQzMzhlZGQxYzNmNWI5NWNiZGRlMzhlZmY3ODU0ZjczMDQzN2JhMTBiZjFhIn0
```

phần sign bằng generate = đoạn mã ở dưới.

```
function d(t) {
            var e = n(269)(),
                r = t.url.substr(1),
                a = r + o.b + e;
            if (void 0 !== t.data)
                if (t.data instanceof FormData) {
                    var u,
                        d = new FormData(),
                        h = "",
                        f = c(t.data.entries());
                    try {
                        for (f.s(); !(u = f.n()).done; ) {
                            var p = u.value;
                            -1 === l.indexOf(p[0]) && (d.append(p[0], p[1]), (h += p[1]));
                        }
                    } catch (t) {
                        f.e(t);
                    } finally {
                        f.f();
                    }
                    a = r + Object.values(h).join("") + o.b + e;
                } else {
                    var m = s.a.omit(t.data, l);
                    a = r + Object.values(m).join("") + o.b + e;
                }
            else if (void 0 !== t.params) {
                var v = s.a.omit(t.params, l);
                a = r + Object.values(v).join("") + o.b + e;
            }
            var g = { jti: e, iss: r, sub: o.a, exp: Math.floor(Date.now() / 1e3) + 3600 };
            return i.a.jws.JWS.sign("HS256", '{"alg":"HS256", "typ":"JWT"}', g, a);
        }
```

`a = r + xxx + o.b + e;`

Phần `r +xxx + o.b` thì easy nhưng thằng `e` hiện tại đang là NodeJS process.pid, khả năng là ko có cách nào bem từ frontend. @lelinhtinh có cao kiến gì ko? :D

**Comment by nntoan** [comment]
P/s: Đã tìm ra solution cho MCT :) ETA: Chủ nhật release.

**Comment by nghia9a5** [comment]
> P/s: Đã tìm ra solution cho MCT :) ETA: Chủ nhật release.

fix luôn bachngocsach bác ơi, tks bác nhiều

**Comment by nntoan** [comment]
v1.0.0 ready rồi nhé: https://github.com/nntoan/UserScripts/blob/master/MCT_downloader/MCT_downloader.user.js

Các bạn download tạm từ GitHub, hiện chưa push lên GreasyFork được do có lỗi của GreasyFork ko chấp nhận URL của jsDeliver. Mình đang nghiên cứu cách fix.

**Comment by lelinhtinh** [comment]
> P/s: Đã tìm ra solution cho MCT :) ETA: Chủ nhật release.

Mình thấy MTC nó có SSR luôn mà, đâu cần phải dùng API nhỉ?

**Comment by lelinhtinh** [comment]
> > P/s: Đã tìm ra solution cho MCT :) ETA: Chủ nhật release.
> 
> Mình thấy MTC nó có SSR luôn mà, đâu cần phải dùng API nhỉ?

Ah thì ra cái danh sách chương, dùng API đúng ngon hơn thật 👍

**Comment by nntoan** [comment]
> > > P/s: Đã tìm ra solution cho MCT :) ETA: Chủ nhật release.
> > 
> > 
> > Mình thấy MTC nó có SSR luôn mà, đâu cần phải dùng API nhỉ?
> 
> Ah thì ra cái danh sách chương, dùng API đúng ngon hơn thật 👍

Hồi xưa viết crawler toàn capture network của mobile app để lấy API của TTV với TruyenCV mà. API thì nó nhanh hơn mà lại phục vụ được nhiều mục đích.

**Comment by erispro** [comment]
web truyen yy ko còn dùng được nữa

Vào Th 7, 3 thg 10, 2020 vào lúc 12:15 Toan Nguyen <
notifications@github.com> đã viết:

**Comment by dokthancau** [comment]
thêm trang tải metruyenchu.com vs sangtacviet.com dc k ad, truyencv nó chuyển qua trang metruyenchu rồi. sangtacviet nó đọc truyện vip đồng nhân khá tốt mong ad làm thêm 🍡

**Comment by hianalyst** [comment]
> thêm trang tải metruyenchu.com vs sangtacviet.com dc k ad, truyencv nó chuyển qua trang metruyenchu rồi. sangtacviet nó đọc truyện vip đồng nhân khá tốt mong ad làm thêm 🍡

mê truyện chữ thì có rồi bác ơi, của bác [nntoan](url) đấy

**Comment by hianalyst** [comment]
à mà nay bên VOZ cũng có 1 bác làm 1 trang truyện tàu dịch máy, bác có thể làm thêm dc ko ạ
địa chỉ web là chivi.xyz á

**Comment by nghia9a5** [comment]
https://metruyenchu.com/ lại lỗi code rồi bác, fix lại giúp anh em với, tks bác
