### ISSUE TITLE
TruyenCV Lỗi không download được

### ISSUE THREAD

**Issue by gianghd** [lelinhtinh/Userscript#62]
Mình vừa check thì có vẻ như do không load được image nên phát sinh lỗi này
>Uncaught Cover data is not allowed

Khi view trực tiếp image https://truyencv.com/images/poster/do-nhi-vi-su-khong-xuong-nui-poster-20200419-220x330.jpg
Thì server đang trả ra lỗi:

> Invalid src mime type: 
> Query String : src=poster/do-nhi-vi-su-khong-xuong-nui-poster-20200419.jpg&w=220&h=330&zc=0
> TimThumb version : 1.19

**Comment by lelinhtinh** [comment]
Quên mất bug này, nay vào lại không thấy bug :laughing:
Tuy vậy, mình cũng thêm ngoại lệ cho phần cover, sau này sẽ không bị lỗi này nữa.
