### ISSUE TITLE
Thêm trang http://tuthienbao.com/ vào được không b ?!

### ISSUE THREAD

**Issue by lucifer208** [lelinhtinh/Userscript#63]
trên trang này này nhiều truyện cổ scan full hay lắm b

**Comment by lelinhtinh** [comment]
Mình có thể làm mấy truyện chuẩn thứ tự mỗi post một chapter như này: http://tuthienbao.com/forum/forumdisplay.php?f=1014
Còn mấy kiểu khác thì tạm bỏ qua nhé.
