### ISSUE TITLE
đổi tên folder - chapter khi tải xuống

### ISSUE THREAD

**Issue by Skennix** [lelinhtinh/Userscript#65]
Chào bạn, script rất ngon, bạn xem thử có thêm chức năng  này vào script được không?
đánh số chương là tên truyện + 001, 002 ... 010, 011, .... 100, 101 ...

**Comment by lelinhtinh** [comment]
Mình lấy theo trên trang truyện thôi, vì có trường hợp số chương không theo thứ tự, phụ chương, v.v... Nếu đánh theo số mà lại khác chương sẽ dễ gây nhầm lẫn. 

Trường hợp bạn vẫn muốn làm vậy, thì có thể **Ctrl+A** chọn toàn bộ chương truyện, nhấn **F2** rename, gõ tên truyện và **Enter**. Cách này sẽ cho kết quả: **Tên truyện (123)**, cũng tạm đúng ý bạn. 
Còn muốn đẹp hơn có thể tìm các tool rename chuyên dụng, sẽ có tùy chỉnh chính xác những gì bạn cần.
