### ISSUE TITLE
Tải truyện trên playerduo.com

### ISSUE THREAD

**Issue by lelinhtinh** [lelinhtinh/Userscript#67]
https://forum.blogtruyen.vn/tool/manga-comic-downloader-44325#cmt-964629

**Comment by jhin1m** [comment]
trước em soi thấy thằng playerduo nó dùng js để tách 1 ảnh làm 3 phần, mỗi phần bị lệch nhau. giờ em soi lại thấy không tách nữa thím ạ :3 pro js cho cao kiến...
![image](https://user-images.githubusercontent.com/24205147/101670758-296d7500-3a86-11eb-8324-09f4b9ea8682.png)

**Comment by lelinhtinh** [comment]
Việc tách hay không tách là do người đăng truyện chọn.
Mình chưa có ý định làm script tải trên trang này do cấu trúc nó hơi khác để dùng trong Manga Comic Downloader, có thể phải làm script riêng.

Lướt qua mã nguồn thì hình như có vài kiểu xử lý chương truyện, về kiểu nối ảnh thì các bước sẽ là:
```
// Lấy SECURITY_CODE sau khi đăng nhập
https://store.mideman.net/api/version.php

// Danh sách chương
https://playerduo.com/api/group-service/albums/ALBUM_ID/posts?security_code=SECURITY_CODE

// Dữ liệu từng chương
https://playerduo.com/api/group-service/posts/POST_ID/posts?security_code=SECURITY_CODE
```

Xử lý dữ liệu chương truyện thì bạn tìm 2 hàm tính tọa độ `getPosition` và nối ảnh `invitedImage` trong mã nguồn của họ _(có thể sẽ bị thay đổi trong tương lai)_:
```
https://playerduo.com/static/js/main.57ef1351.chunk.js
https://playerduo.com/static/js/10.1158239d.chunk.js
```
[main.57ef1351.chunk.js.txt](https://github.com/lelinhtinh/Userscript/files/5670293/main.57ef1351.chunk.js.txt)
[10.1158239d.chunk.js.txt](https://github.com/lelinhtinh/Userscript/files/5670292/10.1158239d.chunk.js.txt)

**Comment by jhin1m** [comment]
e thấy bên cuutruyen cũng làm y hệt như này.

**Comment by jhin1m** [comment]
![image](https://user-images.githubusercontent.com/24205147/114755312-b0f42900-9d83-11eb-8012-3a8c06a583e2.png)
Chào bác, những chương hiện ảnh đầy đủ thì e có thể get được qua api, nhưng có vài chương có nút xem thêm như hình trên, get từ api thì nó hiện mỗi ảnh đầu tiên. Bác chỉ em với ạ, e cảm ơn nhiều!
