### ISSUE TITLE
Manga Comic Downloader

### ISSUE THREAD

**Issue by wernser412** [lelinhtinh/Userscript#68]
Manga Comic Downloader for :
https://tmohentai.com/   
https://lectortmo.com/
https://hentai-id.tv/

**Comment by lelinhtinh** [comment]
Sorry, **Manga Comic Downloader** only supports some websites from Vietnam. Please check out [nHentai Downloader](https://sleazyfork.org/vi/scripts/16088-nhentai-downloader), or use other great apps like [HakuNeko](https://github.com/manga-download/hakuneko), [FMD](https://github.com/riderkick/FMD), [Tachiyomi](https://github.com/inorichi/tachiyomi),...
