### ISSUE TITLE
Không tải được trên nhattruyen.com

### ISSUE THREAD

**Issue by mycroftz1** [lelinhtinh/Userscript#69]
một vài bộ từ nettruyen chuyển hướng nhattruyen nên tải không được.

**Comment by lelinhtinh** [comment]
Bạn gửi link mấy bộ đấy xem, mình tìm không thấy.

**Comment by mycroftz1** [comment]
đa số là mấy bộ manhwa 18+.
http://www.nettruyen.com/tim-truyen/han-quoc-114?status=-1&sort=10&page=2
bạn click thử vài bộ như : khoá học chuyện ấy, my office, thông số tình yêu,...

**Comment by lelinhtinh** [comment]
@mycroftz1 cập v2.10.1 nhé
