### ISSUE TITLE
Công nghệ chống copy của chương vip của TruyenYY

### ISSUE THREAD

**Issue by lelinhtinh** [lelinhtinh/Userscript#71]
Mấy bác cho em hỏi với. Truyenyy giờ có cái công nghệ chống copy của chương vip, kiểu nó tự chèn 1 thẻ html vào content. Các bác ai biết công nghệ kiểu đó keysearch là gì ko ạ???

_Originally posted by @dragonlord4747 in https://github.com/lelinhtinh/Userscript/issues/24#issuecomment-663384260_

**Comment by lelinhtinh** [comment]
Thường thì đọc được sẽ copy được.

- Khó nhất là kiểu render text thành image, dù vậy với công nghệ OCR hiện tại cũng lấy được khá nhiều nội dung. Hơn nữa lưu image sẽ ngốn thêm bandwidth và không responsive được, nên sẽ ít web muốn dùng cách này.
- Ẩn một số từ, dùng css content để hiển thị. Cách này khi copy mà không để ý sẽ bị thiếu nội dung, nhưng vẫn có cách tải được. Chèn thẻ HTML bạn nói có thể là cách này, mình không có acc VIP nên không kiểm tra được. Nếu đúng là nó thì nội dung sẽ nằm trong attribute của thẻ đó, hoặc nếu họ dùng class thì sẽ có một thẻ style chứa content cho class đấy.
- Các kiểu chặn khác bằng JavaScript khác như disable text selection, override copy, ... thì rất dễ vượt qua.

**Comment by dragonlord4747** [comment]
> Thường thì đọc được sẽ copy được.
> 
> * Khó nhất là kiểu render text thành image, dù vậy với công nghệ OCR hiện tại cũng lấy được khá nhiều nội dung. Hơn nữa lưu image sẽ ngốn thêm bandwidth và không responsive được, nên sẽ ít web muốn dùng cách này.
> * Ẩn một số từ, dùng css content để hiển thị. Cách này khi copy mà không để ý sẽ bị thiếu nội dung, nhưng vẫn có cách tải được. Chèn thẻ HTML bạn nói có thể là cách này, mình không có acc VIP nên không kiểm tra được. Nếu đúng là nó thì nội dung sẽ nằm trong attribute của thẻ đó, hoặc nếu họ dùng class thì sẽ có một thẻ style chứa content cho class đấy.
> * Các kiểu chặn khác bằng JavaScript khác như disable text selection, override copy, ... thì rất dễ vượt qua.

Dạ em cảm ơn .Trang kia nó load từ api ra nên em muốn bắt chước mà ko hiểu nó lm kiểu gì. :(((((

**Comment by lelinhtinh** [comment]
Trước đây mình có viết một plugin [hidetext](https://github.com/lelinhtinh/hidetext) cho kết quả tương tự ([demo](https://rawcdn.githack.com/lelinhtinh/hidetext/master/demo/index.html)), nhưng thường thì người ta render trên server.

Mình không rõ có thư viện nào làm việc này không, nhưng nguyên lý cơ bản khá dễ:

- Replace `một từ hoặc cụm từ` thành thẻ HTML `<span class="hidden-text" data-text="một từ hoặc cụm từ"></span>`.
- Thêm vào CSS:  `.hidden-text:after{content:attr(data-text)}`

**Comment by dragonlord4747** [comment]
> Trước đây mình có viết một plugin [hidetext](https://github.com/lelinhtinh/hidetext) cho kết quả tương tự ([demo](https://rawcdn.githack.com/lelinhtinh/hidetext/master/demo/index.html)), nhưng thường thì người ta render trên server.
> 
> Mình không rõ có thư viện nào làm việc này không, nhưng nguyên lý cơ bản khá dễ:
> 
> * Replace `một từ hoặc cụm từ` thành thẻ HTML `<span class="hidden-text" data-text="một từ hoặc cụm từ"></span>`.
> * Thêm vào CSS:  `.hidden-text:after{content:attr(data-text)}`
Vâng, để em thử nghiên cứu theo hướng này xem.

**Comment by lelinhtinh** [comment]
Còn vài kiểu khác mình gặp khi tải truyện:

- Mã hóa text, thường dùng nhất là thuật toán AES sẽ yêu cầu một key để giải mã. Tuy nhiên để người dùng đọc được thì key này sẽ được ẩn giấu, có thể có mã hóa đâu đó trong web, nên dù hơi tốn công vẫn sẽ tìm được cách giải mã. Dùng cách này sẽ tốn tài nguyên server để mã hóa, có thể không cache được nếu mã hóa theo request, ngoài ra còn ảnh hưởng nghiêm trọng đến SEO web.
- Chèn Zero-width space để theo dấu, đánh bản quyền. Việc này từng khiến mình gặp lỗi khi tạo EPUB do các ký tự này gây lỗi ở các trình đọc XHTML cũ. Cách này cũng vô ích, vì rất dể loại bỏ chúng.
- Xáo trộn nội dung, sau đó dùng JavaScript để sắp xếp lại thứ tự đúng. Kiểu này mình chỉ mới gặp trong các trang truyện tranh, tuy nhiên vẫn áp dụng cho truyện chữ được. Vì phải chứa script trong web, nên sẽ vẫn lấy được nội dung đúng, nhưng cách này sẽ làm các trang crawl hàng loạt đau đầu, lấy vài nghìn bộ mới phát hiện lỗi. Nhưng sau đó họ sẽ crawl lại từ đầu, đến lúc đó bạn sẽ đau đầu vì lại bị ngốn thêm bandwidth vô ích.
- Xác minh hành vi người dùng, làm chậm truy vấn liên tục (TruyenYY có dùng hoặc là server họ chậm thật). Nếu làm quá gắt như đòi mật khẩu, xác thực captcha sẽ làm giảm lượng khách truy cập, làm nhẹ nhẹ như TruyenYY thì lâu lâu lại có người than web chậm vì bị chặn nhầm, trước kia họ từng chặn thẳng khách nào lướt trang nhanh gần 2 phút. Nếu dùng CloudFlare thì chỉ cần thêm referer vào header là lại tải được.

**Comment by lelinhtinh** [comment]
@dragonlord4747 Nay mới có dịp ngó code chương VIP của truyenYY, nó là kiểu chèn code rác vào nội dung chương và chặn copy. 
Kiểu này giống truyenCV trước đây, nhưng họ chỉ chèn 1 chuỗi nhỏ chứ không toàn bộ chương như truyenYY. Nguyên lý cũng là split string và replace thôi.

Mình thấy nó chỉ có tác dụng duy nhất là làm chậm tải, do chương vip bị chia làm 3 phần, phải tốn đến 4 request mới tải xong. Nên nhiều khả năng là code chay chứ không có thư viện hay thuật toán nào đâu.

**Comment by dokthancau** [comment]
với trang wikidich chống ddos cua cloudflare thì vượt qua thế nào đc bạn? 🍡

**Comment by lelinhtinh** [comment]
> với trang wikidich chống ddos cua cloudflare thì vượt qua thế nào đc bạn?

Đừng DDoS nó thì tải bình thường thôi, khi nào bị block thì delay vài giây rồi tải lại. Nếu delay tầm 2 phút mà còn không được nữa thì chắc hẳn do bạn cào web họ quá nhiều rồi, lúc đó phải tính đường khác chứ script không giải quyết được đâu.

**Comment by dragonlord4747** [comment]
giờ em mới giở xem code của bác. Bác cho e hỏi sử dụng như nào ấy ạ???

Vào Th 6, 7 thg 8, 2020 vào lúc 01:53 Thành Thân Thiện <
notifications@github.com> đã viết:

**Comment by lelinhtinh** [comment]
Tải hết 3 phần, lọc code rác rồi nối lại.
https://github.com/lelinhtinh/Userscript/blob/931d49fe8eab7683a70e51cd691b0c53961c9034/truyenYY_downloader/truyenYY_downloader.user.js#L80-L119

**Comment by dragonlord4747** [comment]
là trực tiếp dán vào vào console của trình duyệt hay cài kiểu extension ạ???

**Comment by lelinhtinh** [comment]
Cài kiểu extension, như trước khi cài script bạn cần cài một trình quản lý userscripts, ví dụ: [Violentmonkey](https://violentmonkey.github.io/get-it/).

**Comment by dragonlord4747** [comment]
em cảm ơn ạ

Vào Th 3, 16 thg 3, 2021 vào lúc 14:14 Thành Thân Thiện <
***@***.***> đã viết:
