### ISSUE TITLE
Thêm trang truyện raw

### ISSUE THREAD

**Issue by tienok2004** [lelinhtinh/Userscript#75]
Tool của bác thật tuyệt vời. Mình toàn thích tải truyện offline nên gặp tool của bác thiệt là ghiền quá đi mà :D.
Bác có thể thêm source https://manhwa18.net/ và https://manytoon.com/ được k ạ. Em hay dùng các trang này để down raw mà bất tiện quá :D.
Thanks bác vì 1 cái tool rất rất bổ ích.

**Comment by lelinhtinh** [comment]
@tienok2004 cập nhật [MCD@v1.4.0](https://openuserjs.org/scripts/baivong/MCD) nhé.
