### ISSUE TITLE
Lỗi tải chương VIP trên truyenYY

### ISSUE THREAD

**Issue by lelinhtinh** [lelinhtinh/Userscript#76]
truyenyy download chuong VIP bi loi "Dang Tai Noi Dung Vip" fix lai gium voi.

__Originally posted by @thejack99 in https://github.com/lelinhtinh/Userscript/issues/58#issuecomment-670010105__

**Comment by lelinhtinh** [comment]
Lỗi này thì chịu, mình không có acc VIP. Mà hình như acc VIP có luôn EPUB mà cần gì tải nhỉ?

**Comment by thejack99** [comment]
Bây giờ không lấy đc epub nữa rồi bác ơi, scripts của bác lấy đc epub về nhưng khi mở ra mấy chương Vip không xem đc, nó hiện “Đang Tải Nội Dung Vip” Truyện này mình mua chương Vip full rồi.


Sent from Yahoo Mail for iPad


On Thursday, August 6, 2020, 10:51 AM, Thành Thân Thiện <notifications@github.com> wrote:




Lỗi này thì chịu, mình không có acc VIP. Mà hình như acc VIP có luôn EPUB mà cần gì tải nhỉ?

**Comment by lelinhtinh** [comment]
Thế thử tắt script của mình xem, VIP có sẵn chức năng download EPUB rồi.

**Comment by thejack99** [comment]
Bây giờ hết được rồi bác ơi, TruyenYY tắt chức năng đó rồi, nếu được bác cho mình FB, mình gửi Ad Vip TruyenYY cho bác test thử

**Comment by lelinhtinh** [comment]
@thejack99 https://m.me/100006502359009

**Comment by thejack99** [comment]
Bác check ib giúp mình


Sent from Yahoo Mail for iPhone


On Thursday, August 6, 2020, 11:20 AM, Thành Thân Thiện <notifications@github.com> wrote:




@thejack99 https://m.me/100006502359009

**Comment by lelinhtinh** [comment]
Xem lại thì thấy phải tài khoản **Premium** (mua riêng, khác VIP) mới có chức năng xóa quảng cáo với tải EPUB.

**Comment by lelinhtinh** [comment]
Resolves by https://github.com/lelinhtinh/Userscript/commit/0bde72d55d34a4bc8b8a0e11a1697779223374cb
