### ISSUE TITLE
Comparing scripts with others

### ISSUE THREAD

**Issue by DonaldTsang** [lelinhtinh/Userscript#77]
Comparing JS/CSS beautify with https://greasyfork.org/en/scripts/24150-highlight-every-code with https://github.com/hoothin/UserScripts/blob/master/Highlight%20Every%20Code/Highlight%20Every%20Code.user.js what would be the difference?

NOTE: there is also https://greasyfork.org/en/scripts/10608-syntaxify which only does partial highlight

**Comment by lelinhtinh** [comment]
I don't understand your problem. If you want to sync data from Github to GreasyFork then [set up a webhook](https://greasyfork.org/users/webhook-info).

**Comment by DonaldTsang** [comment]
I meant that https://greasyfork.org/en/scripts/16111-javascript-css-beautify and https://greasyfork.org/en/scripts/24150-highlight-every-code seem very different, but they claim to do the same thing.

**Comment by lelinhtinh** [comment]
The links in your first post are about Highlight Every Code by @hoothin.

---

My script automatically highlights all the code from JavaScript URL. 
For example: https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js

![image](https://user-images.githubusercontent.com/5460915/90331000-9c387900-dfdb-11ea-867d-7633dd55a55c.png)

---

Highlight Every Code by @hoothin highlight only the selected code.

![image](https://user-images.githubusercontent.com/5460915/90330994-8c209980-dfdb-11ea-83cc-f40d0edbbe6e.png)

**Comment by DonaldTsang** [comment]
@lelinhtinh one last question: is it possible to apply the same principle to Python and other languages?
- https://github.com/prettier/prettier can replace Beautify
- https://github.com/PrismJS/prism or https://github.com/syntaxhighlighter/syntaxhighlighter or https://github.com/ccampbell/rainbow can replace Highlight.js

**Comment by lelinhtinh** [comment]
You have found the answer yourself.

**Comment by DonaldTsang** [comment]
Is it possible for you to publish a variant to Greasyfork?

**Comment by lelinhtinh** [comment]
If you want to use a library for GM scripts, look for its browser version. 
For Prettier: https://prettier.io/docs/en/browser.html

**Comment by lelinhtinh** [comment]
Prettier now: https://github.com/lelinhtinh/Userscript/commit/98bf30c12d39f607283ca9f1909866a21e05cc7e

**Comment by DonaldTsang** [comment]
Testing it out, but somewhat not working. Try this.
https://raw.githubusercontent.com/hydrusnetwork/hydrus/master/hydrus/core/HydrusNetwork.py

**Comment by lelinhtinh** [comment]
Please update to [v4.1.0](https://greasyfork.org/vi/scripts/16111-javascript-css-beautify?version=838245).
