### ISSUE TITLE
Lỗi cách dòng khi tải TruyenYY

### ISSUE THREAD

**Issue by lelinhtinh** [lelinhtinh/Userscript#79]
tải bên yy toàn lỗi cách dòng admin ơi 
![image](https://user-images.githubusercontent.com/69828779/90459983-6a660600-e0f2-11ea-836f-8e8d44e50fef.png)

_Originally posted by @erispro in https://github.com/lelinhtinh/Userscript/issues/58#issuecomment-675197986_

**Comment by lelinhtinh** [comment]
Script của mình tải xuống là EPUB mà, đâu phải TXT nhỉ?

**Comment by erispro** [comment]
thì epub những mình chuyển qua txt cũng như epub no lỗi như nhau ah admin ơi


Vào Th 7, 22 thg 8, 2020 vào lúc 00:19 Thành Thân Thiện <
notifications@github.com> đã viết:

**Comment by lelinhtinh** [comment]
Nếu được thì gửi mình tài khoản hoặc teamview mình kiểm tra lỗi https://m.me/100006502359009

**Comment by erispro** [comment]
web truyện yy bị gì rồi tải nó toàn đứng không chịu chạy chương

Vào Th 7, 26 thg 9, 2020 vào lúc 20:58 Thành Thân Thiện <
notifications@github.com> đã viết:
