### ISSUE TITLE
truyencv và metruyenchu

### ISSUE THREAD

**Issue by gianghd** [lelinhtinh/Userscript#81]
Hiện tại (chắc là vì lý do quảng cáo) nên họ tách ra làm nhiều site khác nhau.
Một số truyện thì vẫn tồn tại trong truyencv, nhiều truyện mới thì họ cho sang metruyenchu.

mình thử để @match https://metruyenchu.com/truyen/* mà nó không matching.
Nhờ cao thủ support :)

**Comment by lelinhtinh** [comment]
Cấu trúc site khác nhau mà. Mình tính update truyencv downloader mà thấy nó vẫn còn sống nên thôi, gộp vào cái novel downloader luôn.

**Comment by lelinhtinh** [comment]
Cấu trúc site khác nhau nên phải chỉnh trong code nữa. Còn vTruyen với NuHiep nữa, để gom vào Novel Downloader luôn.
