### ISSUE TITLE
Nhờ ad thêm chức năng tải epub cho trang metruyenchu.com

### ISSUE THREAD

**Issue by tienok2004** [lelinhtinh/Userscript#82]
Trang mới này tách ra từ truyencv toàn truyện hay. Mong ad xem sét thêm trang này trong tool tải epub.

Thanks ad nhiều, chúc ad sức khoẻ :D

**Comment by nntoan** [comment]
@tienok2004 Mình có tạo script cho Metruyenchu rồi nha bạn: https://greasyfork.org/en/scripts/412350-metruyenchu-downloader
