### ISSUE TITLE
Hoitruyentranh không download được.

### ISSUE THREAD

**Issue by jhin1m** [lelinhtinh/Userscript#84]
Hoitruyentranh ko down được nữa thím ơi :3

**Comment by jhin1m** [comment]
Các chap hình như lưu theo ID post thì phải thím ạ. 
https://hoitruyentranh.com/load-post-data?&thread_id=549427

**Comment by lelinhtinh** [comment]
> Các chap hình như lưu theo ID post thì phải thím ạ.
> https://hoitruyentranh.com/load-post-data?&thread_id=549427

Đúng là nó đấy, phải thêm token nữa để lấy link ảnh rồi mới tải được. Hôm qua có thấy mà cày game [Hades](https://store.steampowered.com/app/1145360/Hades/) xong quên mất :laughing:

**Comment by jhin1m** [comment]
e tải vẫn lỗi thím ạ :3 
![image](https://user-images.githubusercontent.com/24205147/101280668-f2386300-37fc-11eb-95e6-d3610defc205.png)

**Comment by lelinhtinh** [comment]
Với truyện đó thì về lại bản cũ [v2.11.6](https://greasyfork.org/vi/scripts/369802-manga-comic-downloader?version=849450) sẽ tải được. Không ngờ nó có 2 kiểu tải truyện, biết đâu còn kiểu 3, 4, .... :cry:

**Comment by lelinhtinh** [comment]
Hình như là nó luân phiên giữa 2 kiểu tải thì phải, mấy truyện mình xem lúc trưa cũng chuyển về kiểu tải cũ rồi.
Bỏ cả 2 vào cho chắc. Cập nhật lên bản mới nhất nhé.
