### ISSUE TITLE
[REQUEST] Chọn chương download trên truyenyy

### ISSUE THREAD

**Issue by tracer8** [lelinhtinh/Userscript#89]
Hi bạn,
Bạn có thể cho thêm 1 options cho chọn chương để download trên truyenyy được ko ạ? Vì có 1 số truyện mình chỉ cần tải 1 số chương nhất định, tải hết thì lâu quá.
Cám ơn bạn!

**Comment by lelinhtinh** [comment]
Nhấp **chuột phải** lên nút download và nhập mã chương bắt đầu tải, ví dụ: `chuong-23.html`, nó sẽ tải từ vị trí đó đến cuối.
Không có chức năng chọn chương kết thúc, tuy nhiên bạn có thể nhấp **chuột trái** để dừng tải bất kỳ lúc nào.

**Comment by tracer8** [comment]
ồ, mình ko biết có chức năng này. Cám ơn bạn nhiều!
