### ISSUE TITLE
Sao không có lựa chọn lưu file dưới dạng JPG

### ISSUE THREAD

**Issue by LinhCainNguyen** [lelinhtinh/Userscript#90]
Cho mình hỏi sao dowload truyện lại dưới dạng CBZ vậy? mình thấy đuôi như thế không phổ biến lắm. Mong được hỗ trợ thêm đuôi JPG

**Comment by lelinhtinh** [comment]
Mỗi chap truyện chứa nhiều ảnh JPG (hoặc PNG, WEBP, BMP).
Script của mình không có lựa chọn tải xuống từng ảnh, mà nó sẽ nén tất cả ảnh vào một file nén CBZ.

Về bản chất thì CBZ chính là ZIP, nhưng được đổi tên vì mục đích nhận diện cho các app đọc truyện tranh chuyên dụng. Ví dụ [OpenComic](https://github.com/ollm/OpenComic) (Desktop), [Villain](https://villain.js.org/) (Web), ....

Bạn có thể thay đổi cấu hình bằng cách sửa mã nguồn ở dòng 99 `outputExt`:
https://github.com/lelinhtinh/Userscript/blob/931d49fe8eab7683a70e51cd691b0c53961c9034/manga_comic_downloader/manga_comic_downloader.user.js#L99

CBZ có thể được bổ sung thông tin truyện như tên, tác giả, thể loại, ... nhưng chưa có quy chuẩn quốc tế nào. Có một vài cấu hình của các app đọc truyện phổ biến ngày trước, nhưng giờ thậm chí app đó cũng ngừng phát triển. Ghi chú ở #34

Ngoài ra còn có CBR là kiểu đổi tên của RAR, nhưng đây là định dạng độc quyền nên không tạo được trên web.

**Comment by tienok2004** [comment]
Cái mình cần đây rồi. Hồi đầu toàn phải tự đổi đuôi thành zip mới giải nén được, h thì hiểu cách sửa mã nguồn.

Thanks ad
