### ISSUE TITLE
Mình có để đặt hàng bạn viết script riêng cho mình được không

### ISSUE THREAD

**Issue by tienok2004** [lelinhtinh/Userscript#91]
Mình đang muốn nhờ bạn viết giúp mình viết 1 script nén truyện theo trang web yêu cầu được không? Liên hệ với bạn như thế nào?

**Comment by lelinhtinh** [comment]
Cảm ơn bạn đã quan tâm nhưng hiện tại mình không có thời gian nhận thêm dự án ngoài.
