### ISSUE TITLE
Không download được ở các trang truyện tranh

### ISSUE THREAD

**Issue by meomap13** [lelinhtinh/Userscript#93]
Hi bạn, Nhờ bạn xem giúp tool hiện không down được các truyện tranh ở các trang
hamtruyen.com, otakusan.net, nettruyen, truyentranh8, comicvn... Lỗi tương tự như hình đính kèm. Cám ơn bạn.
![hamtruyen](https://user-images.githubusercontent.com/74047262/120955537-c9793200-c77b-11eb-8eb5-9f24250b8c11.png)

**Comment by lelinhtinh** [comment]
Fixed in v3.3.0
