### ISSUE TITLE
Bilibili can't resolve

### ISSUE THREAD

**Issue by paiky** [lelinhtinh/Userscript#95]
**Describe the bug**
Bilibili can't resolve.

**To Reproduce**
1. Go to 'https://www.bilibili.com/bangumi/play/ep408123'

**Screenshots**
[![fQs8w4.md.png](https://z3.ax1x.com/2021/08/08/fQs8w4.md.png)](https://imgtu.com/i/fQs8w4)

**Context (name + version):**
- Script: [e.g. Anti Social Locker 1.1.4]
- UserScript manager: [e.g. Violentmonkey 2.12.7]
- Browser: [e.g. Google Chrome  86.0.4240.183]

**Comment by lelinhtinh** [comment]
This script only supports 9 plugins (_listed [here](https://greasyfork.org/scripts/21137-anti-social-locker)_). Please find another script at [Greasyfork](https://greasyfork.org/scripts/by-site/bilibili.com?filter_locale=0).
